In [88]:
# importing needed libraries and models
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import ExtraTreesClassifier,AdaBoostClassifier,BaggingClassifier
from sklearn.linear_model import LinearRegression
from sklearn.neural_network import MLPClassifier
from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from datetime import datetime

plt.style.use('fivethirtyeight')


%matplotlib inline
%config InlineBackend.figure_format = 'retina'

# Loading and pre processing the two approuches datasets

### Approuch 1 preprocessing

In [2]:
# loading the approuch one dataset
app1 = pd.read_csv('app1')
# taking the radiant team only, so the model dont be sensitive to the second team
app1 = app1.loc[app1.radiant == 1]
app1.head()

avg_mmr  num_mmr  tot_intel  tot_stren  tot_agi  tot_range  tot_melee  \
0     4257        2          1          3        1          1          4   
2     4147        5          1          3        1          1          4   
4     4811        6          2          1        2          3          2   
6     3148        3          3          1        1          3          2   
8     4261        5          1          2        2          2          3   

   radiant  day_of_week  month           ...            lobby_type_Normal  \
0        1            0      8           ...                            0   
2        1            0      8           ...                            0   
4        1            0      8           ...                            0   
6        1            0      8           ...                            0   
8        1            0      8           ...                            0   

   lobby_type_Ranked  lobby_type_practise  game_mode_All_Draft  \
0                  1                    0                    1   
2                  1                    0                    0   
4                  1                    0                    1   
6                  1                    0                    1   
8                  1                    0                    1   

   game_mode_All_Random  game_mode_Captains_Draft  game_mode_Captains_mode  \
0                     0                         0                        0   
2                     0                         0                        0   
4                     0                         0                        0   
6                     0                         0                        0   
8                     0                         0                        0   

   game_mode_Least_played  game_mode_Random_Draft  game_mode_Single_Draft  
0                       0                       0                       0  
2                       0                       1                       0  
4                       0                       0                       0  
6                       0                       0                       0  
8                       0                       0                       0  

[5 rows x 138 columns]

In [3]:
# splitting target and featuresnapprouch one
y_app1 = app1.radiant_win_True
X_app1 = app1.drop(labels=['radiant_win_True','day_of_week',
                           'month','week','hour','match_id'],axis=1)

X_app1.head()

avg_mmr  num_mmr  tot_intel  tot_stren  tot_agi  tot_range  tot_melee  \
0     4257        2          1          3        1          1          4   
2     4147        5          1          3        1          1          4   
4     4811        6          2          1        2          3          2   
6     3148        3          3          1        1          3          2   
8     4261        5          1          2        2          2          3   

   radiant  Juggernaut  Axe           ...            lobby_type_Normal  \
0        1           1    0           ...                            0   
2        1           0    1           ...                            0   
4        1           0    1           ...                            0   
6        1           0    0           ...                            0   
8        1           0    0           ...                            0   

   lobby_type_Ranked  lobby_type_practise  game_mode_All_Draft  \
0                  1                    0                    1   
2                  1                    0                    0   
4                  1                    0                    1   
6                  1                    0                    1   
8                  1                    0                    1   

   game_mode_All_Random  game_mode_Captains_Draft  game_mode_Captains_mode  \
0                     0                         0                        0   
2                     0                         0                        0   
4                     0                         0                        0   
6                     0                         0                        0   
8                     0                         0                        0   

   game_mode_Least_played  game_mode_Random_Draft  game_mode_Single_Draft  
0                       0                       0                       0  
2                       0                       1                       0  
4                       0                       0                       0  
6                       0                       0                       0  
8                       0                       0                       0  

[5 rows x 132 columns]

In [4]:
# train test split
X_train_app1, X_test_app1, y_train_app1, y_test_app1 = train_test_split(X_app1,y_app1,test_size=0.3)


In [6]:
# standerizing the dataframe
scale = StandardScaler()
# fitting and transforming the train data set
X_train_app1 = scale.fit_transform(X_train_app1)
# transforming the test set
X_test_app1 = scale.transform(X_test_app1)

### Approuch two preprocessing

In [99]:
# loading approuch two data set
app2= pd.read_csv('app2')
app2.head()



avg_mmr  diff_intel  diff_stren  diff_agi  diff_range  diff_melee  \
0     4257          -1           2        -1          -2          -4   
1     4147           0          -1         1           0          -4   
2     4811          -1           0         1           0          -2   
3     3148           3          -1        -2           1          -2   
4     4261           0          -1         1           0          -3   

     match_id  radiant_win_True  dire_plyr_1_Abaddon  dire_plyr_1_Alchemist  \
0  3300000109                 0                    0                      0   
1  3300000200                 1                    0                      0   
2  3300000206                 1                    0                      0   
3  3300000404                 1                    0                      0   
4  3300000405                 0                    0                      0   

        ...         rad_plyr_5_Venomancer  rad_plyr_5_Viper  \
0       ...                             0                 0   
1       ...                             0                 0   
2       ...                             0                 0   
3       ...                             0                 0   
4       ...                             0                 0   

   rad_plyr_5_Visage  rad_plyr_5_Warlock  rad_plyr_5_Weaver  \
0                  0                   0                  0   
1                  0                   0                  0   
2                  0                   0                  0   
3                  0                   0                  0   
4                  0                   0                  0   

   rad_plyr_5_Windranger  rad_plyr_5_Winter Wyvern  rad_plyr_5_Witch Doctor  \
0                      0                         0                        0   
1                      0                         0                        0   
2                      0                         0                        0   
3                      0                         0                        0   
4                      0                         0                        0   

   rad_plyr_5_Wraith King  rad_plyr_5_Zeus  
0                       0                0  
1                       0                0  
2                       0                0  
3                       0                0  
4                       0                0  

[5 rows x 1138 columns]

In [100]:
# splitting target and features
y_app2 = app2.radiant_win_True
X_app2 = app2.drop(labels=['radiant_win_True',
                           'match_id'],axis=1)


X_app2.head()

avg_mmr  diff_intel  diff_stren  diff_agi  diff_range  diff_melee  \
0     4257          -1           2        -1          -2          -4   
1     4147           0          -1         1           0          -4   
2     4811          -1           0         1           0          -2   
3     3148           3          -1        -2           1          -2   
4     4261           0          -1         1           0          -3   

   dire_plyr_1_Abaddon  dire_plyr_1_Alchemist  dire_plyr_1_Ancient Apparition  \
0                    0                      0                               0   
1                    0                      0                               0   
2                    0                      0                               0   
3                    0                      0                               0   
4                    0                      0                               0   

   dire_plyr_1_Anti-Mage       ...         rad_plyr_5_Venomancer  \
0                      0       ...                             0   
1                      0       ...                             0   
2                      0       ...                             0   
3                      0       ...                             0   
4                      0       ...                             0   

   rad_plyr_5_Viper  rad_plyr_5_Visage  rad_plyr_5_Warlock  rad_plyr_5_Weaver  \
0                 0                  0                   0                  0   
1                 0                  0                   0                  0   
2                 0                  0                   0                  0   
3                 0                  0                   0                  0   
4                 0                  0                   0                  0   

   rad_plyr_5_Windranger  rad_plyr_5_Winter Wyvern  rad_plyr_5_Witch Doctor  \
0                      0                         0                        0   
1                      0                         0                        0   
2                      0                         0                        0   
3                      0                         0                        0   
4                      0                         0                        0   

   rad_plyr_5_Wraith King  rad_plyr_5_Zeus  
0                       0                0  
1                       0                0  
2                       0                0  
3                       0                0  
4                       0                0  

[5 rows x 1136 columns]

In [101]:
# train test split
X_train_app2, X_test_app2, y_train_app2, y_test_app2 = train_test_split(X_app2,y_app2,test_size=0.3)



In [102]:
# standerizing the dataframe
scale = StandardScaler()
# fitting and transforming the train data set
X_train_app2 = scale.fit_transform(X_train_app2)
# transforming the test set
X_test_app2 = scale.transform(X_test_app2)

### Creating summary score tables for model evaluation

#### Approuch 1

In [35]:
# summary table for approuch one models
summary_models_app1 = {'model':[],'Baseline':[],'train_score':[],'test_score':[],'cross_val_mean':[]}

In [11]:
# summary tabele for approuch one ensamble methods
summary_ensamble_app1 = {'ensamble':[],'Baseline':[],'train_score':[],'test_score':[]}

In [12]:
# taking the baseline for approuch one to evaluate model performace 
baseline_app1 = y_app1.value_counts()[1]/len(y_app1)

#### Approuch 2

In [13]:
# summary table for approuch one models
summary_models_app2 = {'model':[],'Baseline':[],'train_score':[],'test_score':[],'cross_val_mean':[]}

In [148]:
# summary tabele for approuch two ensamble methods
summary_ensamble_app2 = {'ensamble':[],'Baseline':[],'train_score':[],'test_score':[]}

In [15]:
# taking the baseline for approuch two to evaluate model performace 
baseline_app2 = y_app2.value_counts()[1]/len(y_app2)

# Approuch one Gridsearch and Modeling

### Gridsearch App 1

In [65]:
# Decision Tree search parameters
params_app1_dt = {'max_depth':np.arange(20,40),
                 'criterion':['gini','entropy']}

# LogisticR reggression search parameters
params_app1_lr = {'penalty':['l1','l2']}

# MLP Classifier search parameters
params_app1_nnet = {'activation':['identity', 'logistic', 'tanh', 'relu'],
                   'max_iter':[100,200]}

# Nearist nighbor search parameters
params_app1_knn = {'n_neighbors':np.arange(1,10)}


# LinearSVC search parameters
params_app1_svc = {'penalty':['l1','l2'],
                  'max_iter':[1000,200]}

In [17]:
# Decision Tree gridsearch
gr_dt = GridSearchCV(DecisionTreeClassifier(),params_app1_dt,cv=5,n_jobs=-1)
# fitting the grid into approuch one
gr_dt.fit(X_train_app1,y_train_app1)
# displaying the best parameters
gr_dt.best_estimator_

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=20,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [18]:
# Logistic reggression gridsearch
gr_lr = GridSearchCV(LogisticRegression(),params_app1_lr,cv=5,n_jobs=-1)
# fitting the grid into approuch 1
gr_lr.fit(X_train_app1,y_train_app1)
# displaying the best parameters
gr_lr.best_estimator_

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [19]:
# MLP Classifier gridsearch
gr_nnet = GridSearchCV(MLPClassifier(hidden_layer_sizes=(100,70,50,24,10,4)),params_app1_nnet,cv=5,n_jobs=-1)
# fitting the grid into approuch 1
gr_nnet.fit(X_train_app1,y_train_app1)
# displaying the best parameters
gr_nnet.best_estimator_

MLPClassifier(activation='identity', alpha=0.0001, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100, 70, 50, 24, 10, 4),
       learning_rate='constant', learning_rate_init=0.001, max_iter=200,
       momentum=0.9, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [20]:
# nearist nighbor gridsearch
gr_knn = GridSearchCV(KNeighborsClassifier(n_jobs=-1),params_app1_knn,cv=5,n_jobs=-1)
# fitting the grid into approuch 1
gr_knn.fit(X_train_app1,y_train_app1)
# displaying the best parameters
gr_knn.best_estimator_

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
           weights='uniform')

In [66]:
# LinearSVC gridsearch
gr_svc = GridSearchCV(LinearSVC(dual=False),params_app1_svc,cv=5,n_jobs=-1)
# fitting the grid into approuch one
gr_svc.fit(X_train_app1,y_train_app1)
# displaying the best parameters
gr_svc.best_estimator_

LinearSVC(C=1.0, class_weight=None, dual=False, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l1', random_state=None, tol=0.0001,
     verbose=0)

### Modeling App 1

###### Decision tree

In [28]:
# decision tree using the best parameters
dt_app1 = DecisionTreeClassifier(criterion='gini',max_depth=20)
# fitting approuch one data set
dt_app1.fit(X_train_app1,y_train_app1)
# obtaining cross val scores mean
dt_app1_cvm = cross_val_score(dt_app1,X_train_app1,y_train_app1,cv=5).mean()
# printing scores
print('train score: ',dt_app1.score(X_train_app1,y_train_app1))
print('---')
print('test score: ',dt_app1.score(X_test_app1,y_test_app1))
print('---')
print('cross val mean: ',dt_app1_cvm)

train score:  0.6831078131820166
---
test score:  0.5339443312966734
---
cross val mean:  0.5293175038857105


In [34]:
# predicting X test for model evaluation
y_hat_dt_app1 = dt_app1.predict(X_test_app1)
y_hat_dt_app1[0:5]

array([1, 1, 1, 1, 1])

In [36]:
# appending scores and baseline in the summary table
summary_models_app1['model'].append('Decision Tree')
summary_models_app1['Baseline'].append(baseline_app1)
summary_models_app1['train_score'].append(dt_app1.score(X_train_app1,y_train_app1))
summary_models_app1['test_score'].append(dt_app1.score(X_test_app1,y_test_app1))
summary_models_app1['cross_val_mean'].append(dt_app1_cvm)

In [189]:
# displaying feature importance top 5
dt_feat_app1 = pd.DataFrame(X_app1.columns,columns=['feature'])
dt_feat_app1['importance'] = dt_app1.feature_importances_
# displaying in assending orede
dt_feat_app1.sort_values(by='importance',ascending=False).head()

feature  importance
0    avg_mmr    0.191236
1    num_mmr    0.041522
4    tot_agi    0.020183
5  tot_range    0.017799
2  tot_intel    0.017382

###### most target affecting features are the ones shown above

###### Logistic Reggression

In [38]:
# Logistic Reggression using the best parameters
lr_app1 = LogisticRegression(penalty='l2')
# fitting approuch one data set
lr_app1.fit(X_train_app1,y_train_app1)
# obtaining cross val scores mean
lr_app1_cvm = cross_val_score(lr_app1,X_train_app1,y_train_app1,cv=5).mean()
# printing scores
print('train score: ',lr_app1.score(X_train_app1,y_train_app1))
print('---')
print('test score: ',lr_app1.score(X_test_app1,y_test_app1))
print('---')
print('cross val mean: ',lr_app1_cvm)

train score:  0.5736214171395315
---
test score:  0.5667006109979633
---
cross val mean:  0.5536880452395911


In [39]:
# predicting X test for model evaluation
y_hat_lr_app1 = lr_app1.predict(X_test_app1)
y_hat_lr_app1[0:5]

array([1, 1, 0, 1, 1])

In [40]:
# appending scores and baseline in the summary table
summary_models_app1['model'].append('Logistic reggression')
summary_models_app1['Baseline'].append(baseline_app1)
summary_models_app1['train_score'].append(lr_app1.score(X_train_app1,y_train_app1))
summary_models_app1['test_score'].append(lr_app1.score(X_test_app1,y_test_app1))
summary_models_app1['cross_val_mean'].append(lr_app1_cvm)

###### MLP Classifier

In [45]:
# MLP Classifier using the best parameters
nnet_app1 = MLPClassifier(hidden_layer_sizes=(100,70,50,24,10,4),max_iter=200,activation='identity')
# fitting approuch one data set
nnet_app1.fit(X_train_app1,y_train_app1)
# obtaining cross val scores mean
nnet_app1_cvm = cross_val_score(nnet_app1,X_train_app1,y_train_app1,cv=5).mean()
# printing scores
print('train score: ',nnet_app1.score(X_train_app1,y_train_app1))
print('---')
print('test score: ',nnet_app1.score(X_test_app1,y_test_app1))
print('---')
print('cross val mean: ',nnet_app1_cvm)

train score:  0.5709297250109122
---
test score:  0.5609300746775289
---
cross val mean:  0.5502693872151857


In [46]:
# predicting X test for model evaluation
y_hat_nnet_app1 = nnet_app1.predict(X_test_app1)
y_hat_nnet_app1[0:5]

array([1, 1, 0, 1, 1])

In [48]:
# appending scores and baseline in the summary table
summary_models_app1['model'].append('MLP Classifier')
summary_models_app1['Baseline'].append(baseline_app1)
summary_models_app1['train_score'].append(nnet_app1.score(X_train_app1,y_train_app1))
summary_models_app1['test_score'].append(nnet_app1.score(X_test_app1,y_test_app1))
summary_models_app1['cross_val_mean'].append(nnet_app1_cvm)

###### KNearist Nighbor

In [50]:
# KNN using the best parameters
knn_app1 = KNeighborsClassifier(n_jobs=-1,n_neighbors=5)
# fitting approuch one data set
knn_app1.fit(X_train_app1,y_train_app1)
# obtaining cross val scores mean
knn_app1_cvm = cross_val_score(knn_app1,X_train_app1,y_train_app1,cv=5).mean()
# printing scores
print('train score: ',knn_app1.score(X_train_app1,y_train_app1))
print('---')
print('test score: ',knn_app1.score(X_test_app1,y_test_app1))
print('---')
print('cross val mean: ',knn_app1_cvm)

train score:  0.6960570347737524
---
test score:  0.5140868974881195
---
cross val mean:  0.5242973378749297


In [51]:
# predicting X test for model evaluation
y_hat_knn_app1 = knn_app1.predict(X_test_app1)
y_hat_knn_app1[0:5]

array([1, 1, 0, 0, 1])

In [52]:
# appending scores and baseline in the summary table
summary_models_app1['model'].append('KNN')
summary_models_app1['Baseline'].append(baseline_app1)
summary_models_app1['train_score'].append(knn_app1.score(X_train_app1,y_train_app1))
summary_models_app1['test_score'].append(knn_app1.score(X_test_app1,y_test_app1))
summary_models_app1['cross_val_mean'].append(knn_app1_cvm)

###### LinearSVC 

In [69]:
# LinearSVC using the best parameters
svc_app1 = LinearSVC(max_iter=1000,penalty='l1',dual=False)
# fitting approuch one data set
svc_app1.fit(X_train_app1,y_train_app1)
# obtaining cross val scores mean
svc_app1_cvm = cross_val_score(svc_app1,X_train_app1,y_train_app1,cv=5).mean()
# printing scores
print('train score: ',svc_app1.score(X_train_app1,y_train_app1))
print('---')
print('test score: ',svc_app1.score(X_test_app1,y_test_app1))
print('---')
print('cross val mean: ',svc_app1_cvm)

train score:  0.5736214171395315
---
test score:  0.5667006109979633
---
cross val mean:  0.5530333145937365


In [70]:
# predicting X test for model evaluation
y_hat_svc_app1 = svc_app1.predict(X_test_app1)
y_hat_svc_app1[0:5]

array([1, 1, 0, 1, 1])

In [71]:
# appending scores and baseline in the summary table
summary_models_app1['model'].append('SVC')
summary_models_app1['Baseline'].append(baseline_app1)
summary_models_app1['train_score'].append(svc_app1.score(X_train_app1,y_train_app1))
summary_models_app1['test_score'].append(svc_app1.score(X_test_app1,y_test_app1))
summary_models_app1['cross_val_mean'].append(svc_app1_cvm)

### Ensamble methods App 1

###### Adabtive Boosting

In [74]:
# adaBoosting the best performing model along with using its best parameters
ada_app1 = AdaBoostClassifier(LogisticRegression(penalty='l2'))
# Fitting approuch one dataset
ada_app1.fit(X_train_app1,y_train_app1)
# printing scores
print('train score: ',ada_app1.score(X_train_app1,y_train_app1))
print('---')
print('test score: ',ada_app1.score(X_test_app1,y_test_app1))

train score:  0.5718754546777244
---
test score:  0.5677189409368636


In [76]:
# predicting X test for model evaluation
y_hat_ada_app1 = ada_app1.predict(X_test_app1)
y_hat_ada_app1[0:5]

array([1, 1, 0, 1, 1])

In [77]:
# appending the scores and baseline
summary_ensamble_app1['ensamble'].append('AdaBoost')
summary_ensamble_app1['Baseline'].append(baseline_app1)
summary_ensamble_app1['train_score'].append(ada_app1.score(X_train_app1,y_train_app1))
summary_ensamble_app1['test_score'].append(ada_app1.score(X_test_app1,y_test_app1))


###### Extra Tree Classifier

In [80]:
# ExtraTreeClasifier
ext_app1 = ExtraTreesClassifier(n_jobs=-1,max_depth=20)
# Fitting approuch one dataset
ext_app1.fit(X_train_app1,y_train_app1)
# printing scores
print('train score: ',ext_app1.score(X_train_app1,y_train_app1))
print('---')
print('test score: ',ext_app1.score(X_test_app1,y_test_app1))

train score:  0.8673796013385712
---
test score:  0.5390359809911744


Extra tree overfitted the training set

In [81]:
# predicting X test for model evaluation
y_hat_ext_app1 = ext_app1.predict(X_test_app1)
y_hat_ext_app1[0:5]

array([1, 0, 1, 1, 1])

In [82]:
# appending the scores and baseline
summary_ensamble_app1['ensamble'].append('ExtraTreeClassifier')
summary_ensamble_app1['Baseline'].append(baseline_app1)
summary_ensamble_app1['train_score'].append(ext_app1.score(X_train_app1,y_train_app1))
summary_ensamble_app1['test_score'].append(ext_app1.score(X_test_app1,y_test_app1))

In [188]:
# displaying feature importance top 5
ext_feat_app1 = pd.DataFrame(X_app1.columns,columns=['feature'])
ext_feat_app1['importance'] = ext_app1.feature_importances_
# displaying in assending orede
ext_feat_app1.sort_values(by='importance',ascending=False).head()

feature  importance
0    avg_mmr    0.029816
1    num_mmr    0.026770
4    tot_agi    0.023588
6  tot_melee    0.019984
2  tot_intel    0.019969

###### simular to decsion tree feature importance variables, seams like rank info and type totals have the most affect in predicting the target variable

###### Random Forest

In [84]:
# Random forest
forest_app1 = RandomForestClassifier(n_jobs=-1,max_depth=20)
# Fitting approuch one dataset
forest_app1.fit(X_train_app1,y_train_app1)
# printing scores
print('train score: ',forest_app1.score(X_train_app1,y_train_app1))
print('---')
print('test score: ',forest_app1.score(X_test_app1,y_test_app1))

train score:  0.8068529026625928
---
test score:  0.5381873727087576


random forest also overfited the data or choise poor split point

In [85]:
# predicting X test for model evaluation
y_hat_forest_app1 = forest_app1.predict(X_test_app1)
y_hat_forest_app1[0:5]

array([1, 1, 0, 1, 1])

In [86]:
# appending the scores and baseline
summary_ensamble_app1['ensamble'].append('RandomForest')
summary_ensamble_app1['Baseline'].append(baseline_app1)
summary_ensamble_app1['train_score'].append(forest_app1.score(X_train_app1,y_train_app1))
summary_ensamble_app1['test_score'].append(forest_app1.score(X_test_app1,y_test_app1))

In [190]:
# displaying feature importance top 5
forest_feat_app1 = pd.DataFrame(X_app1.columns,columns=['feature'])
forest_feat_app1['importance'] = forest_app1.feature_importances_
# displaying in assending orede
forest_feat_app1.sort_values(by='importance',ascending=False).head()

feature  importance
0    avg_mmr    0.096548
1    num_mmr    0.042423
4    tot_agi    0.033921
3  tot_stren    0.026363
2  tot_intel    0.025602

###### Bagging

In [89]:
# bagging the best performing model along with using its best parameters
bag_app1 = BaggingClassifier(base_estimator=LogisticRegression(penalty='l2'),n_jobs=-1)
# Fitting approuch one dataset
bag_app1.fit(X_train_app1,y_train_app1)
# printing scores
print('train score: ',bag_app1.score(X_train_app1,y_train_app1))
print('---')
print('test score: ',bag_app1.score(X_test_app1,y_test_app1))


train score:  0.5716572093699985
---
test score:  0.564663951120163


In [91]:
# predicting X test for model evaluation
y_hat_bag_app1 = bag_app1.predict(X_test_app1)
y_hat_bag_app1[0:5]

array([1, 1, 0, 1, 1])

In [93]:
# appending the scores and baseline
summary_ensamble_app1['ensamble'].append('Bagging')
summary_ensamble_app1['Baseline'].append(baseline_app1)
summary_ensamble_app1['train_score'].append(forest_app1.score(X_train_app1,y_train_app1))
summary_ensamble_app1['test_score'].append(forest_app1.score(X_test_app1,y_test_app1))

# Approuch Two Gridsearch and Modeling

### Gridsearch App 2
finding the best parameters for the choicen models

In [128]:
# Decision Tree search parameters
params_app2_dt = {'max_depth':np.arange(10,20),
                 'criterion':['gini','entropy']}

# LogisticR reggression search parameters
params_app2_lr = {'penalty':['l1','l2']}

# MLP Classifier search parameters
params_app2_nnet = {'activation':['identity', 'logistic', 'tanh', 'relu'],
                   'max_iter':[100,200]}

# LinearSVC search parameters
params_app2_svc = {'penalty':['l1','l2'],
                  'max_iter':[1000,200]}

In [105]:
# Decision Tree gridsearch
gr_dt_app2 = GridSearchCV(DecisionTreeClassifier(),params_app2_dt,cv=5,n_jobs=-1)
# fitting the grid into approuch one
gr_dt_app2.fit(X_train_app2,y_train_app2)
# displaying the best parameters
gr_dt_app2.best_estimator_

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=19,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [123]:
# Logistic Regression gridsearch
gr_lr_app2 = GridSearchCV(LogisticRegression(),params_app2_lr,cv=5,n_jobs=-1)
# fitting the grid into approuch one
gr_lr_app2.fit(X_train_app2,y_train_app2)
# displaying the best parameters
gr_lr_app2.best_estimator_

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l1', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [124]:
# MLP Classifeir gridsearch
gr_nnet_app2 = GridSearchCV(MLPClassifier(hidden_layer_sizes=(100,70,50,24)),params_app2_nnet,cv=5,n_jobs=-1)
# fitting the grid into approuch one
gr_nnet_app2.fit(X_train_app2,y_train_app2)
# displaying the best parameters
gr_nnet_app2.best_estimator_

/Users/sultan.almuhanna/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='identity', alpha=0.0001, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100, 70, 50, 24), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [129]:
# LinearSVC gridsearch
gr_svc_app2 = GridSearchCV(LinearSVC(dual=False),params_app2_svc,cv=5,n_jobs=-1)
# fitting the grid into approuch one
gr_svc_app2.fit(X_train_app2,y_train_app2)
# displaying the best parameters
gr_svc_app2.best_estimator_

LinearSVC(C=1.0, class_weight=None, dual=False, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

### Modeling App 2

###### Decision Tree

In [106]:
# decision tree using the best parameters
dt_app2 = DecisionTreeClassifier(criterion='gini',max_depth=19)
# fitting approuch two data set
dt_app2.fit(X_train_app2,y_train_app2)
# obtaining cross val scores mean
dt_app2_cvm = cross_val_score(dt_app2,X_train_app2,y_train_app2,cv=5).mean()
# printing scores
print('train score: ',dt_app2.score(X_train_app2,y_train_app2))
print('---')
print('test score: ',dt_app2.score(X_test_app2,y_test_app2))
print('---')
print('cross val mean: ',dt_app2_cvm)

train score:  0.5885348465008002
---
test score:  0.5336048879837068
---
cross val mean:  0.5346283144283872


In [108]:
# predicting X test for model evaluation
y_hat_dt_app2 = dt_app2.predict(X_test_app2)
y_hat_dt_app2[0:5]

array([1, 1, 1, 1, 1])

In [109]:
# appending scores and baseline in the summary table
summary_models_app2['model'].append('Decision Tree')
summary_models_app2['Baseline'].append(baseline_app2)
summary_models_app2['train_score'].append(dt_app2.score(X_train_app2,y_train_app2))
summary_models_app2['test_score'].append(dt_app2.score(X_test_app2,y_test_app2))
summary_models_app2['cross_val_mean'].append(dt_app2_cvm)

In [191]:
# displaying feature importance top 5
dt_feat_app2 = pd.DataFrame(X_app2.columns,columns=['feature'])
dt_feat_app2['importance'] = dt_app2.feature_importances_
# displaying in assending orede
dt_feat_app2.sort_values(by='importance',ascending=False).head()

feature  importance
0                  avg_mmr    0.100782
1               diff_intel    0.024012
3                 diff_agi    0.017012
495         dire_plyr_5_Io    0.017008
65   dire_plyr_1_Necrophos    0.014516

###### in feature importance in approuch two the most important features ware the average rank of the match and two diffrence between teams types along with some player hero selctions wich is diffrent from the first approuch.

###### Logistic Regression

In [130]:
# Logistic Reggression using the best parameters
lr_app2 = LogisticRegression(penalty='l1')
# fitting approuch one data set
lr_app2.fit(X_train_app2,y_train_app2)
# obtaining cross val scores mean
lr_app2_cvm = cross_val_score(lr_app2,X_train_app2,y_train_app2,cv=5).mean()
# printing scores
print('train score: ',lr_app2.score(X_train_app2,y_train_app2))
print('---')
print('test score: ',lr_app2.score(X_test_app2,y_test_app2))
print('---')
print('cross val mean: ',lr_app2_cvm)

train score:  0.6521897279208497
---
test score:  0.551255940257977
---
cross val mean:  0.5575430139885578


In [131]:
# predicting X test for model evaluation
y_hat_lr_app2 = lr_app2.predict(X_test_app2)
y_hat_lr_app2[0:5]

array([0, 0, 0, 0, 1])

In [132]:
# appending scores and baseline in the summary table
summary_models_app2['model'].append('Logistic Regreassion')
summary_models_app2['Baseline'].append(baseline_app2)
summary_models_app2['train_score'].append(lr_app2.score(X_train_app2,y_train_app2))
summary_models_app2['test_score'].append(lr_app2.score(X_test_app2,y_test_app2))
summary_models_app2['cross_val_mean'].append(lr_app2_cvm)

###### MLP Classifier

In [133]:
# MLP Classifier using the best parameters
nnet_app2 = MLPClassifier(hidden_layer_sizes=(100,70,50,24),max_iter=200,activation='identity')
# fitting approuch one data set
nnet_app2.fit(X_train_app2,y_train_app2)
# obtaining cross val scores mean
nnet_app2_cvm = cross_val_score(nnet_app2,X_train_app2,y_train_app2,cv=5).mean()
# printing scores
print('train score: ',nnet_app2.score(X_train_app2,y_train_app2))
print('---')
print('test score: ',nnet_app2.score(X_test_app2,y_test_app2))
print('---')
print('cross val mean: ',nnet_app2_cvm)

train score:  0.6452058780736214
---
test score:  0.5521045485403937
---
cross val mean:  0.5539777902708424


In [134]:
# predicting X test for model evaluation
y_hat_nnet_app2 = nnet_app2.predict(X_test_app2)
y_hat_nnet_app2[0:5]

array([0, 1, 0, 0, 1])

In [135]:
# appending scores and baseline in the summary table
summary_models_app2['model'].append('MLP Classifier')
summary_models_app2['Baseline'].append(baseline_app2)
summary_models_app2['train_score'].append(nnet_app2.score(X_train_app2,y_train_app2))
summary_models_app2['test_score'].append(nnet_app2.score(X_test_app2,y_test_app2))
summary_models_app2['cross_val_mean'].append(nnet_app2_cvm)

###### Knearist nighbor

In [136]:
# KNN using the best parameters
knn_app2 = KNeighborsClassifier(n_jobs=-1,n_neighbors=3)
# fitting approuch one data set
knn_app2.fit(X_train_app2,y_train_app2)
# obtaining cross val scores mean
knn_app2_cvm = cross_val_score(knn_app2,X_train_app2,y_train_app2,cv=5).mean()
# printing scores
print('train score: ',knn_app2.score(X_train_app2,y_train_app2))
print('---')
print('test score: ',knn_app2.score(X_test_app2,y_test_app2))
print('---')
print('cross val mean: ',knn_app2_cvm)

train score:  0.7589116833988069
---
test score:  0.5044127630685675
---
cross val mean:  0.5109844373160489


Nearist nighbor also overfit the training set ending up with a poor score for the test set

In [137]:
# predicting X test for model evaluation
y_hat_knn_app2 = knn_app2.predict(X_test_app2)
y_hat_knn_app2[0:5]

array([0, 0, 0, 1, 1])

In [138]:
# appending scores and baseline in the summary table
summary_models_app2['model'].append('KNN')
summary_models_app2['Baseline'].append(baseline_app2)
summary_models_app2['train_score'].append(knn_app2.score(X_train_app2,y_train_app2))
summary_models_app2['test_score'].append(knn_app2.score(X_test_app2,y_test_app2))
summary_models_app2['cross_val_mean'].append(knn_app2_cvm)

###### LinearCVS

In [139]:
# LinearSVC using the best parameters
svc_app2 = LinearSVC(max_iter=1000,penalty='l2')
# fitting approuch one data set
svc_app2.fit(X_train_app2,y_train_app2)
# obtaining cross val scores mean
svc_app2_cvm = cross_val_score(svc_app2,X_train_app2,y_train_app2,cv=5).mean()
# printing scores
print('train score: ',svc_app2.score(X_train_app2,y_train_app2))
print('---')
print('test score: ',svc_app2.score(X_test_app2,y_test_app2))
print('---')
print('cross val mean: ',svc_app2_cvm)

train score:  0.5908627964498764
---
test score:  0.5327562797012899
---
cross val mean:  0.5376835212804656


In [141]:
# predicting X test for model evaluation
y_hat_svc_app2 = svc_app2.predict(X_test_app2)
y_hat_svc_app2[0:5]

array([1, 0, 0, 0, 1])

In [143]:
# appending scores and baseline in the summary table
summary_models_app2['model'].append('SVC')
summary_models_app2['Baseline'].append(baseline_app2)
summary_models_app2['train_score'].append(svc_app2.score(X_train_app2,y_train_app2))
summary_models_app2['test_score'].append(svc_app2.score(X_test_app2,y_test_app2))
summary_models_app2['cross_val_mean'].append(svc_app2_cvm)

### Ensamble methods App 2

###### Adabtive boosting

In [144]:
# adaBoosting the best performing model along with using its best parameters
ada_app2 = AdaBoostClassifier(LogisticRegression(penalty='l2'))
# Fitting approuch one dataset
ada_app2.fit(X_train_app2,y_train_app2)
# printing scores
print('train score: ',ada_app2.score(X_train_app2,y_train_app2))
print('---')
print('test score: ',ada_app2.score(X_test_app2,y_test_app2))

train score:  0.6476793248945147
---
test score:  0.5502376103190767


In [145]:
# predicting X test for model evaluation
y_hat_ada_app2 = ada_app2.predict(X_test_app2)
y_hat_ada_app2[0:5]

array([0, 0, 0, 0, 1])

In [149]:
# appending the scores and baseline
summary_ensamble_app2['ensamble'].append('AdaBoost')
summary_ensamble_app2['Baseline'].append(baseline_app2)
summary_ensamble_app2['train_score'].append(ada_app2.score(X_train_app2,y_train_app2))
summary_ensamble_app2['test_score'].append(ada_app2.score(X_test_app2,y_test_app2))

###### Extra Tree classifier

In [150]:
# ExtraTreeClasifier
ext_app2 = ExtraTreesClassifier(n_jobs=-1,max_depth=19)
# Fitting approuch one dataset
ext_app2.fit(X_train_app2,y_train_app2)
# printing scores
print('train score: ',ext_app2.score(X_train_app2,y_train_app2))
print('---')
print('test score: ',ext_app2.score(X_test_app2,y_test_app2))

train score:  0.6525534701003929
---
test score:  0.5358112695179905


In [151]:
# predicting X test for model evaluation
y_hat_ext_app2 = ext_app2.predict(X_test_app2)
y_hat_ext_app2[0:5]

array([0, 1, 1, 1, 1])

In [152]:
# appending the scores and baseline
summary_ensamble_app2['ensamble'].append('ExtraTreeClassifier')
summary_ensamble_app2['Baseline'].append(baseline_app2)
summary_ensamble_app2['train_score'].append(ext_app2.score(X_train_app2,y_train_app2))
summary_ensamble_app2['test_score'].append(ext_app2.score(X_test_app2,y_test_app2))

In [192]:
# displaying feature importance top 5
ext_feat_app2 = pd.DataFrame(X_app2.columns,columns=['feature'])
ext_feat_app2['importance'] = ext_app2.feature_importances_
# displaying in assending orede
ext_feat_app2.sort_values(by='importance',ascending=False).head()

feature  importance
65          dire_plyr_1_Necrophos    0.013763
290  dire_plyr_3_Nature's Prophet    0.011663
990           rad_plyr_4_Silencer    0.010684
495                dire_plyr_5_Io    0.009695
37        dire_plyr_1_Enchantress    0.008956

###### for the extra tree classifier looks like the affecting features are hero picks, but due to resualts that are near the baseline these heros wont be consedered as the most affecting picks for matches

###### Random Forest

In [153]:
# Random forest
forest_app2 = RandomForestClassifier(n_jobs=-1,max_depth=19)
# Fitting approuch one dataset
forest_app2.fit(X_train_app2,y_train_app2)
# printing scores
print('train score: ',forest_app2.score(X_train_app2,y_train_app2))
print('---')
print('test score: ',forest_app2.score(X_test_app2,y_test_app2))

train score:  0.6695766041030118
---
test score:  0.5269857433808554


In [154]:
# predicting X test for model evaluation
y_hat_forest_app2 = forest_app2.predict(X_test_app2)
y_hat_forest_app2[0:5]

array([1, 1, 0, 0, 0])

In [155]:
# appending the scores and baseline
summary_ensamble_app2['ensamble'].append('RandomForest')
summary_ensamble_app2['Baseline'].append(baseline_app2)
summary_ensamble_app2['train_score'].append(forest_app2.score(X_train_app2,y_train_app2))
summary_ensamble_app2['test_score'].append(forest_app2.score(X_test_app2,y_test_app2))

In [193]:
# displaying feature importance top 5
forest_feat_app2 = pd.DataFrame(X_app2.columns,columns=['feature'])
forest_feat_app2['importance'] = forest_app2.feature_importances_
# displaying in assending orede
forest_feat_app2.sort_values(by='importance',ascending=False).head()

feature  importance
0     avg_mmr    0.038094
3    diff_agi    0.011280
4  diff_range    0.010899
5  diff_melee    0.010515
1  diff_intel    0.008737

###### Bagging

In [156]:
# bagging the best performing model along with using its best parameters
bag_app2 = BaggingClassifier(base_estimator=LogisticRegression(penalty='l2'),n_jobs=-1)
# Fitting approuch one dataset
bag_app2.fit(X_train_app2,y_train_app2)
# printing scores
print('train score: ',bag_app2.score(X_train_app2,y_train_app2))
print('---')
print('test score: ',bag_app2.score(X_test_app2,y_test_app2))



train score:  0.6514622435617634
---
test score:  0.5504073319755601


In [157]:
# predicting X test for model evaluation
y_hat_bag_app2 = bag_app2.predict(X_test_app2)
y_hat_bag_app2[0:5]

array([0, 1, 0, 0, 1])

In [158]:
# appending the scores and baseline
summary_ensamble_app2['ensamble'].append('Bagging')
summary_ensamble_app2['Baseline'].append(baseline_app2)
summary_ensamble_app2['train_score'].append(bag_app2.score(X_train_app2,y_train_app2))
summary_ensamble_app2['test_score'].append(bag_app2.score(X_test_app2,y_test_app2))

# Model Evaluation

### Approuch 1 Evaluation

###### printing the classification report of the best performing models in approuch 1

In [160]:
# first by converting the summary table from a dictionary to a dataframe for models
# displaying the summary table
summary_models_app1 = pd.DataFrame(summary_models_app1)
summary_models_app1

model  Baseline  train_score  test_score  cross_val_mean
0         Decision Tree  0.532284     0.683108    0.533944        0.529318
1  Logistic reggression  0.532284     0.573621    0.566701        0.553688
2  Logistic reggression  0.532284     0.573621    0.566701        0.553688
3        MLP Classifier  0.532284     0.570930    0.560930        0.550269
4                   KNN  0.532284     0.696057    0.514087        0.524297
5                   SVC  0.532284     0.573621    0.566701        0.553033

###### Logistic Regression, MLP classifier and support vector classfier performed better than the other models for approuch 1 with approximatly 3 percent. and the three mentioned models performed better than the baseline, not that much but its an improvement with almost also 3 percent. Lastly those three models predictions will be used for the classification reports and confusion matrix.

In [167]:
# classification report for logistic reggression
from sklearn.metrics import classification_report
print('Logistic Regression classification report')
print('---')
print(classification_report(y_test_app1,y_hat_lr_app1))

Logistic Regression classification report
---
             precision    recall  f1-score   support

          0       0.55      0.42      0.47      2745
          1       0.58      0.70      0.63      3147

avg / total       0.56      0.57      0.56      5892



In [168]:
# classification report for MLP Classifir
print('MLP Classifier classification report')
print('---')
print(classification_report(y_test_app1,y_hat_nnet_app1))

MLP Classifier classification report
---
             precision    recall  f1-score   support

          0       0.54      0.44      0.48      2745
          1       0.58      0.67      0.62      3147

avg / total       0.56      0.56      0.56      5892



In [169]:
# classification report for LinearSVC
print('LinearSVC classification report')
print('---')
print(classification_report(y_test_app1,y_hat_svc_app1))

LinearSVC classification report
---
             precision    recall  f1-score   support

          0       0.55      0.41      0.47      2745
          1       0.58      0.70      0.63      3147

avg / total       0.56      0.57      0.56      5892



###### classification reports for model resaults are simular to each other for approuch one

###### Displaying the confusion matrix to see the correctly and incorrectly classified instences

In [173]:
from sklearn.metrics import confusion_matrix
print('Logistic confusion matrix')
print('----')
print(confusion_matrix(y_test_app1,y_hat_lr_app1))

Logistic confusion matrix
----
[[1143 1602]
 [ 951 2196]]


In [174]:
print('MLP confusion matrix')
print('----')
print(confusion_matrix(y_test_app1,y_hat_nnet_app1))

MLP confusion matrix
----
[[1205 1540]
 [1047 2100]]


In [175]:
print('SVC confusion matrix')
print('----')
print(confusion_matrix(y_test_app1,y_hat_svc_app1))

SVC confusion matrix
----
[[1139 1606]
 [ 947 2200]]


###### printing the classification report of the best performing Ensamble method in approuch 1

In [161]:
# first by converting the summary table from a dictionary to a dataframe for ensamble methods
summary_ensamble_app1 = pd.DataFrame(summary_ensamble_app1)
summary_ensamble_app1

ensamble  Baseline  train_score  test_score
0             AdaBoost  0.532284     0.571875    0.567719
1             AdaBoost  0.532284     0.571875    0.567719
2  ExtraTreeClassifier  0.532284     0.867380    0.539036
3         RandomForest  0.532284     0.806853    0.538187
4         RandomForest  0.532284     0.806853    0.538187
5              Bagging  0.532284     0.806853    0.538187

###### Logistic Regression Boosted using Adabditve boosting performed better than the other ensamble methods for approuch 1 with approximatly 3 percent. the othe methods overfitted on the training data while performed poorly on the test set and the method performed better than the baseline, not that much but its an improvement with almost also 3 percent.  Moreover the evaluation will include only the Logistic regression boosted and the boosted logistic model performed better than the Logistic model by small percent.

In [176]:
# classification report for MLP Classifir
print('AdaBtive Boosting classification report')
print('---')
print(classification_report(y_test_app1,y_hat_ada_app1))

AdaBtive Boosting classification report
---
             precision    recall  f1-score   support

          0       0.55      0.42      0.47      2745
          1       0.58      0.70      0.63      3147

avg / total       0.56      0.57      0.56      5892



###### scores did not show much change from the original Logistic model

In [177]:
print('Boosted Logistic confusion matrix')
print('----')
print(confusion_matrix(y_test_app1,y_hat_ada_app1))

Boosted Logistic confusion matrix
----
[[1142 1603]
 [ 944 2203]]


### Approuch 2 Evaluation

In [178]:
# first by converting the summary table from a dictionary to a dataframe for models
# displaying the summary table
summary_models_app2 = pd.DataFrame(summary_models_app2)
summary_models_app2

model  Baseline  train_score  test_score  cross_val_mean
0         Decision Tree  0.532284     0.588535    0.533605        0.534628
1  Logistic Regreassion  0.532284     0.652190    0.551256        0.557543
2        MLP Classifier  0.532284     0.645206    0.552105        0.553978
3                   KNN  0.532284     0.758912    0.504413        0.510984
4                   SVC  0.532284     0.590863    0.532756        0.537684
5                   SVC  0.532284     0.590863    0.532756        0.537684

###### only Logistic reggression and MLP classifier performed better the baseline by 2 percent wich is an improvment along with performing better than the other used models. knn overfitted on the training data set, for the evaluation only the two mentioned models will be used for classification report and confusion matrix.

In [179]:
print('Logistic Regression classification report')
print('---')
print(classification_report(y_test_app2,y_hat_lr_app2))

Logistic Regression classification report
---
             precision    recall  f1-score   support

          0       0.53      0.47      0.50      2790
          1       0.57      0.62      0.59      3102

avg / total       0.55      0.55      0.55      5892



In [180]:
print('MLP Classifier classification report')
print('---')
print(classification_report(y_test_app2,y_hat_nnet_app2))

MLP Classifier classification report
---
             precision    recall  f1-score   support

          0       0.53      0.43      0.47      2790
          1       0.56      0.67      0.61      3102

avg / total       0.55      0.55      0.55      5892



###### Checking the confusion matrices for both Logistic and MLP classifier models to see the correctly and incorrecly classified instences

In [181]:
print('Logistic  Model confusion matrix')
print('----')
print(confusion_matrix(y_test_app2,y_hat_lr_app2))

Logistic  Model confusion matrix
----
[[1314 1476]
 [1168 1934]]


In [182]:
print('MLP Classifier confusion matrix')
print('----')
print(confusion_matrix(y_test_app2,y_hat_nnet_app2))

MLP Classifier confusion matrix
----
[[1186 1604]
 [1035 2067]]


###### printing the classification report of the best performing Ensamble method in Approuch 2

In [183]:
# first by converting the summary table from a dictionary to a dataframe for ensamble methods
summary_ensamble_app2 = pd.DataFrame(summary_ensamble_app2)
summary_ensamble_app2

ensamble  Baseline  train_score  test_score
0             AdaBoost  0.532284     0.647679    0.550238
1  ExtraTreeClassifier  0.532284     0.652553    0.535811
2         RandomForest  0.532284     0.669577    0.526986
3              Bagging  0.532284     0.651462    0.550407

###### bagging and Boosting using Logistic reggression ware the best ensamble methods used in approuch 2, performing better than the baseline by 2 percent and better the models with approximitly 3 percent wich is an improvment. those mentioned ensamble methods will be used for evaluation.

In [184]:
# classification report for adabtive boosting
print('AdaBtive Boosting classification report')
print('---')
print(classification_report(y_test_app2,y_hat_ada_app2))

AdaBtive Boosting classification report
---
             precision    recall  f1-score   support

          0       0.53      0.47      0.50      2790
          1       0.57      0.62      0.59      3102

avg / total       0.55      0.55      0.55      5892



In [185]:
# classification report forBagging
print('bagging classification report')
print('---')
print(classification_report(y_test_app2,y_hat_bag_app2))

bagging classification report
---
             precision    recall  f1-score   support

          0       0.53      0.47      0.50      2790
          1       0.57      0.62      0.59      3102

avg / total       0.55      0.55      0.55      5892



###### Checking the confusion matrices for both boosted Logistic and bagged Logistic ensamble methods for approuch 2 to see the correctly and incorrecly classified instences

In [186]:
print('Boosted Logistic confusion matrix')
print('----')
print(confusion_matrix(y_test_app1,y_hat_ada_app1))

Boosted Logistic confusion matrix
----
[[1142 1603]
 [ 944 2203]]


In [187]:
print('Bagged Logistic confusion matrix')
print('----')
print(confusion_matrix(y_test_app1,y_hat_bag_app1))

Bagged Logistic confusion matrix
----
[[1122 1623]
 [ 942 2205]]


### Model  Evaluation
regarding the approuches used in this project, approuch 1 wich was each match combined into two observations that describe each team hero picks and taking the hero types and attack type total for each regardless of the hero pick position. approuch 1 performed in modeling and ensambling better than approuch two wich contains all match pick including hero pick postioning and taking the diffrence in each team for the total types and attack types. performed better by 1 percent for the best models in both approuches wich is also an improvment from the baseline, for the final model choice approuch one Boosted Logistic regression model that their parameters ware takien from a gridsearch.